version: '2'

networks:
  app-network:
    driver: bridge
services:
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=123456
      - REDIS_AOF_ENABLE=no
    restart: always
    ports:
      - '6379:6379'
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
